from __future__ import annotations
class MarketDataError(Exception): ...
class ProviderUnavailableError(MarketDataError): ...
class SymbolNotFoundError(MarketDataError): ...
class DownloadFailedError(MarketDataError): ...
